CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)  NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP     NOT NULL,
    created_on         TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    published_on       TIMESTAMP,
    paid               BOOLEAN     DEFAULT FALSE,
    participant_limit  INT         DEFAULT 0,
    request_moderation BOOLEAN     DEFAULT TRUE,
    state              VARCHAR(20) DEFAULT 'PENDING' CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),

    location_lat       NUMERIC(9, 6) NOT NULL,
    location_lon       NUMERIC(9, 6) NOT NULL,

    category_id        BIGINT        NOT NULL,
    initiator_id       BIGINT        NOT NULL,

    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_event_user FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE
);

CREATE TABLE participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED')),
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,

    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_request_user FOREIGN KEY (requester_id) REFERENCES users (id)
);
